# -*- coding: utf-8 -*-
"""KWM_server_1.0.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4SqViWJT12s6Jd6Gt0ZvHlxfNi_FfnH

Kugelwolkenmodell-Chemie. Erstellt JSON Objekt.

Prokrustes Algorithmus. Sowas wie Kurven fitten. Auch inverse Kinematik. Andockproblem.
"""

import numpy as np
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uuid

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==============================================================================
# 1. DAS PERIODENSYSTEM DER GEOMETRIEN (Die "Bauanleitung")
# ==============================================================================
# Jedes Element definiert seinen Geometrie-Typ, die Gesamt-Elektronenanzahl
# und seine Standard-Visualisierung (Farbe/Größe im Browser).
ELEMENT_PROFIL = {
    "H":  {"geo": "KUGEL",     "valenzelektronen": 1, "radius": 0.18, "farbe": 0xffffff},
    "Li": {"geo": "KUGEL",     "valenzelektronen": 1, "radius": 0.25, "farbe": 0x9b59b6},
    "Be": {"geo": "HANTEL",    "valenzelektronen": 2, "radius": 0.28, "farbe": 0xd35400},
    "B":  {"geo": "DREIECK",   "valenzelektronen": 3, "radius": 0.28, "farbe": 0x1abc9c},
    "C":  {"geo": "TETRAEDER", "valenzelektronen": 4, "radius": 0.30, "farbe": 0x34495e},
    "N":  {"geo": "TETRAEDER", "valenzelektronen": 5, "radius": 0.30, "farbe": 0x2980b9},
    "O":  {"geo": "TETRAEDER", "valenzelektronen": 6, "radius": 0.30, "farbe": 0xe74c3c},
    "F":  {"geo": "TETRAEDER", "valenzelektronen": 7, "radius": 0.30, "farbe": 0x27ae60},
}

def generiere_wolken_vektoren(geo_typ, r=0.6):
    """Berechnet die rein geometrischen Richtungsvektoren für die Wolken."""
    if geo_typ == "KUGEL":
        return [np.array([0.0, 0.0, 0.0])]

    elif geo_typ == "HANTEL":
        return [np.array([0.0, 0.0, r]), np.array([0.0, 0.0, -r])]

    elif geo_typ == "DREIECK":
        return [
            np.array([0.0, r, 0.0]),
            np.array([r * np.sin(np.radians(120)), r * np.cos(np.radians(120)), 0.0]),
            np.array([-r * np.sin(np.radians(120)), r * np.cos(np.radians(120)), 0.0])
        ]

    elif geo_typ == "TETRAEDER":
        t_coords = [[1, 1, 1], [-1, -1, 1], [-1, 1, -1], [1, -1, -1]]
        return [np.array(c) / np.linalg.norm(c) * r for c in t_coords]

    return []


# ==============================================================================
# 2. DIE DATENSTRUKTUR FÜR ATOME UND DIE WELT
# ==============================================================================
class Kugelwolke:
    def __init__(self, id_num, elektronen, richtung_lokal):
        self.id = id_num
        self.elektronen = elektronen  # 1 = reaktiv (blau), 2 = frei (grau), 3 = gebunden (grün)
        self.richtung_lokal = richtung_lokal

class Atom:
    def __init__(self, uid, symbol, position=[0.0, 0.0, 0.0]):
        self.uid = uid
        self.symbol = symbol
        self.position = np.array(position, dtype=float)
        self.rotation = np.eye(3)
        self.wolken = []

        # Holen uns das Profil aus dem "Wörterbuch"
        profil = ELEMENT_PROFIL[symbol]
        vektoren = generiere_wolken_vektoren(profil["geo"])

        # Elektronen intelligent auf die Wolken verteilen
        ve_uebrig = profil["valenzelektronen"]
        anzahl_wolken = len(vektoren)

        # Jede Wolke bekommt erstmal mindestens 1 Elektron (Hundsche Regel vereinfacht)
        wolken_e = [0] * anzahl_wolken
        for i in range(ve_uebrig):
            wolken_e[i % anzahl_wolken] += 1

        for i, vec in enumerate(vektoren):
            self.wolken.append(Kugelwolke(id_num=i, elektronen=wolken_e[i], richtung_lokal=vec.tolist()))

    def to_dict(self):
        profil = ELEMENT_PROFIL[self.symbol]
        return {
            "uid": self.uid,
            "symbol": self.symbol,
            "position": self.position.tolist(),
            "rotation": self.rotation.flatten().tolist(),
            "radius": profil["radius"],
            "farbe": profil["farbe"],
            "wolken": [w.__dict__ for w in self.wolken]
        }

# Der Weltzustand startet jetzt komplett leer und dynamisch!
WELT_ZUSTAND = {}


# ==============================================================================
# 3. DIE API ENDPOINTS (Kurz, klar, funktional)
# ==============================================================================
@app.get("/status")
def get_status():
    return {uid: atom.to_dict() for uid, atom in WELT_ZUSTAND.items()}


@app.post("/erzeuge_atom")
def erzeuge_atom(daten: dict):
    """Fügt der Szene dynamisch ein neues Atom hinzu."""
    symbol = daten["symbol"]
    # Generiere eine eindeutige ID (z.B. C_a83f) und eine leicht zufällige Startposition
    uid = f"{symbol}_{uuid.uuid4().hex[:4]}"
    zufalls_pos = (np.random.rand(3) - 0.5) * 4.0

    WELT_ZUSTAND[uid] = Atom(uid, symbol, position=zufalls_pos.tolist())
    return {"status": "success", "uid": uid}

@app.post("/binde")
def binde_atome(daten: dict):
    atom_A = WELT_ZUSTAND[daten["atom_A_id"]]
    atom_B = WELT_ZUSTAND[daten["atom_B_id"]]
    wolken_A_ids = daten["wolken_A_ids"]
    wolken_B_ids = daten["wolken_B_ids"]

    anzahl_wolken = len(wolken_A_ids)

    # Lokale Vektoren extrahieren
    punkte_A_lokal = [np.array(atom_A.wolken[i].richtung_lokal) for i in wolken_A_ids]
    punkte_B_lokal = [np.array(atom_B.wolken[i].richtung_lokal) for i in wolken_B_ids]

    # Geometrische Sortierung (Verdrehungsschutz bei Mehrfachbindungen)
    if anzahl_wolken > 1:
        sortierte_B_lokal = []
        uebrige_B = list(punkte_B_lokal)
        for pA in punkte_A_lokal:
            # Zuordnung über den minimalen Abstand zur invertierten A-Wolke
            index_des_naechsten = min(range(len(uebrige_B)), key=lambda idx: np.linalg.norm((-pA) - uebrige_B[idx]))
            sortierte_B_lokal.append(uebrige_B.pop(index_des_naechsten))
        punkte_B_lokal = sortierte_B_lokal

    # 1. DYNAMISCHER ABSTAND NACH BINDUNGSORDNUNG (KWM_constraints)
    if anzahl_wolken == 3:    fester_abstand = 1.02  # Dreifachbindung (Flächen-Teilung)
    elif anzahl_wolken == 2:  fester_abstand = 1.12  # Doppelbindung (Kanten-Teilung)
    else:                     fester_abstand = 1.25  # Einfachbindung (Punkt-Teilung)

    # Zentralatom-Schutz prüfen (Ist Atom A bereits in einem Molekülverband?)
    atom_A_schon_gebunden = any(w.elektronen == 3 for w in atom_A.wolken)

    # 2. BINDUNGSACHSE BESTIMMEN
    if atom_A_schon_gebunden:
        # Globale Richtung der ausgewählten Wolken von A bestimmt die starre Achse
        A_ausgerichtet = [atom_A.rotation @ p for p in punkte_A_lokal]
        zentrum_A_global = np.mean(A_ausgerichtet, axis=0)
        bindungs_richtung = zentrum_A_global / np.linalg.norm(zentrum_A_global)
    else:
        # Falls A frei ist, nutzen wir den aktuellen Einflugvektor von B
        aktuelle_differenz = atom_B.position - atom_A.position
        distanz = np.linalg.norm(aktuelle_differenz)
        bindungs_richtung = aktuelle_differenz / distanz if distanz > 1e-3 else np.array([1.0, 0.0, 0.0])

    # Position von Atom B fixieren
    atom_B.position = atom_A.position + bindungs_richtung * fester_abstand

    # 3. ROTATION FÜR ATOM A (nur falls es noch ungebunden im Raum schwebte)
    if not atom_A_schon_gebunden:
        zentrum_A_lokal = np.mean(punkte_A_lokal, axis=0)
        if np.linalg.norm(zentrum_A_lokal) > 1e-5:
            z_norm = zentrum_A_lokal / np.linalg.norm(zentrum_A_lokal)
            v = np.cross(z_norm, bindungs_richtung)
            c = np.dot(z_norm, bindungs_richtung)
            if not np.allclose(v, 0):
                s = np.linalg.norm(v)
                kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
                atom_A.rotation = np.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s ** 2))

    # Globale Ausrichtung der bindenden A-Wolken für den Prokrustes-Abgleich ermitteln
    A_global_wolken = [atom_A.rotation @ p for p in punkte_A_lokal]

    # 4. EXAKTE GEOMETRISCHE RESTRIKTIONEN NACH BINDUNGSORDNUNG
    if anzahl_wolken == 1:
        # Einfachbindung: Kollineare Ausrichtung der Partnerwolke via SVD
        B_ziel = -A_global_wolken[0]
        B_start = punkte_B_lokal[0]

        H = np.outer(B_start, B_ziel)
        U, S, Vt = np.linalg.svd(H)
        R_B = Vt.T @ U.T
        if np.linalg.det(R_B) < 0:
            Vt[-1, :] *= -1
            R_B = Vt.T @ U.T
        atom_B.rotation = R_B

    elif anzahl_wolken == 2:
        # Doppelbindung (Kanten-Teilung): Rigider Koplanaritäts-Schutz
        B_ziel = -np.array(A_global_wolken)
        B_start = np.array(punkte_B_lokal)

        # Normalenvektor der Bindungsebene berechnen, um Torsionskippen zu verhindern
        normalen_A = np.cross(A_global_wolken[0], A_global_wolken[1])
        normalen_B = np.cross(punkte_B_lokal[0], punkte_B_lokal[1])

        # SVD-Matrizen mit den Normalenvektoren als 3. Achse stabilisieren
        B_ziel = np.vstack([B_ziel, normalen_A]) if 'normalen_A' in locals() else np.vstack([B_ziel, normalen_A])
        B_start = np.vstack([B_start, normalen_B])

        H = B_start.T @ B_ziel
        U, S, Vt = np.linalg.svd(H)
        R_B = Vt.T @ U.T
        if np.linalg.det(R_B) < 0:
            Vt[-1, :] *= -1
            R_B = Vt.T @ U.T
        atom_B.rotation = R_B

    elif anzahl_wolken == 3:
        # Dreifachbindung (Flächen-Teilung): Bestimme die kompromisslose Ausrichtung Gesicht-zu-Gesicht
        B_ziel = -np.array(A_global_wolken)
        B_start = np.array(punkte_B_lokal)

        # SVD Basis-Ausrichtung
        H = B_start.T @ B_ziel
        U, S, Vt = np.linalg.svd(H)
        R_B = Vt.T @ U.T
        if np.linalg.det(R_B) < 0:
            Vt[-1, :] *= -1
            R_B = Vt.T @ U.T

        # --- ANTI-UMKLAPP-SCHUTZ (Orientierungs-Validierung) ---
        # Wo zeigt das Zentrum der 3 B-Wolken nach der reinen SVD-Ausrichtung hin?
        zentrum_B_nach_svd = np.mean([R_B @ p for p in punkte_B_lokal], axis=0)

        # Das Wolkenzentrum MUSS zurück zu Atom A zeigen (Skalarprodukt < 0).
        # Ist es > 0, klappt das symmetrische System (z.B. C-C) fälschlicherweise nach außen weg.
        if np.dot(zentrum_B_nach_svd, bindungs_richtung) > 0:
            # Schnitzel-Flip: 180° Drehung um eine orthogonale Achse zur Bindungsachse
            if abs(bindungs_richtung[0]) < 0.9:
                ortho_achse = np.array([1.0, 0.0, 0.0])
            else:
                ortho_achse = np.array([0.0, 1.0, 0.0])
            ortho_achse = np.cross(bindungs_richtung, ortho_achse)
            ortho_achse /= np.linalg.norm(ortho_achse)

            K_ortho = np.array([
                [0, -ortho_achse[2], ortho_achse[1]],
                [ortho_achse[2], 0, -ortho_achse[0]],
                [-ortho_achse[1], ortho_achse[0], 0]
            ])
            R_flip_innen = np.eye(3) + 2 * (K_ortho @ K_ortho) # cos(180)=-1, sin(180)=0
            R_B = R_flip_innen @ R_B

        # --- TORSIONS-KORREKTUR (-60 Grad für "Lücke zu Deckung") ---
        w = bindungs_richtung / np.linalg.norm(bindungs_richtung)
        alpha = np.radians(60)

        cos_a = np.cos(alpha)
        sin_a = np.sin(alpha)
        K_achse = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
        R_torsion = np.eye(3) + sin_a * K_achse + (1 - cos_a) * (K_achse @ K_achse)

        # Finale Rotationsmatrix für Dreifachbindung zusammensetzen
        atom_B.rotation = R_torsion @ R_B

    # 5. ELEKTRONEN-STATUS UPDATEN (Zustand 3 = Gebunden/Grün im Frontend)
    for i in wolken_A_ids: atom_A.wolken[i].elektronen = 3
    for i in wolken_B_ids: atom_B.wolken[i].elektronen = 3

    return {"status": "success", "debug": f"Erfolgreich {anzahl_wolken}-fach starr gebunden."}



@app.post("/reset")
def reset_simulation():
    WELT_ZUSTAND.clear()
    return {"status": "success"}

"""Server starten"""

import multiprocessing
import uvicorn
import nest_asyncio

# Erlaubt verschachtelte Event-Loops in Jupyter/Colab Notebooks
nest_asyncio.apply()

def start_api():
    # Wir übergeben direkt das 'app'-Objekt aus Zelle 1
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="info")

# Server in einen separaten Hintergrundprozess auslagern
server_prozess = multiprocessing.Process(target=start_api)
server_prozess.start()
print("Backend-Server wurde erfolgreich im Hintergrund auf Port 8000 gestartet!")

"""Test server"""

#server_prozess.terminate()
#print("Server gestoppt.")

# 1. Installiere pyngrok
!pip install pyngrok

from pyngrok import ngrok

# ==========================================
# HIER FÜGST DU DEINEN AUTHTOKEN EIN
# ==========================================
# Ersetze 'DEIN_NGROK_AUTHTOKEN_HIER' mit dem langen Code von der ngrok-Webseite
NGROK_TOKEN = "1Y1jBALsPqgA8RQOJd4HDib3Ofh_6HgoK1dPV8iBcKbVvxbQb"

# Dem ngrok-System den Token mitteilen
ngrok.set_auth_token(NGROK_TOKEN)

# Kill any running ngrok processes from this session to free up tunnel slots
# ngrok.kill()

# 2. Jetzt erst den Tunnel zu Port 8000 öffnen
public_url = ngrok.connect(8000, "http")
print("Deine öffentliche API-Zustandsadresse für deine lokale UI lautet:")
print(f"{public_url.public_url}/status")

from fastapi.responses import HTMLResponse

@app.get("/", response_class=HTMLResponse)
def read_root():
    # 1. Lies die lokale index.html ein
    with open("index.html", "r", encoding="utf-8") as f:
        html_content = f.read()

    # 2. Wir suchen NUR nach dem Variablen-Namen und überschreiben die Zuweisung komplett.
    # Egal ob in deiner index.html 'http...' oder 'https...' steht:
    # Wir zwingen das JavaScript dazu, die aktuelle Server-Adresse dynamisch zu ermitteln.

    # Wir ersetzen die alte Zeile komplett mit einer sauberen JavaScript-Anweisung:
    html_content = html_content.replace(
        "const API_URL = 'http://127.0.0.1:8000';",
        "const API_URL = window.location.origin;"
    )

    # Falls du in der index.html schon die https-ngrok-Adresse fest eingetragen hattest,
    # fangen wir das hier sicherheitshalber auch noch ab:
    if "const API_URL = 'https://" in html_content:
        # Wir suchen das Ende der Zeile und ersetzen sie sauber
        start_idx = html_content.find("const API_URL = 'https://")
        end_idx = html_content.find("';", start_idx) + 2
        alte_zeile = html_content[start_idx:end_idx]
        html_content = html_content.replace(alte_zeile, "const API_URL = window.location.origin;")

    return html_content

'''
!pip install clifford
import pytest
import numpy as np
from clifford.g3c import * # Geometrische Algebra G3 für Multi-Vector-Wedge-Validierung

# Dummy-Strukturen für den Testlauf analog zur Server-Logik
def create_tetrahedron_vectors():
    t_coords = [[1, 1, 1], [-1, -1, 1], [-1, 1, -1], [1, -1, -1]]
    return [np.array(c) / np.linalg.norm(c) * 0.6 for c in t_coords]

def test_methane_volume_constraint():
    """Validiert den Tetraeder-Schwerpunkt und das gleichmäßige Volumen von Methan (CH4)."""
    # Kernzentrum C (0-Simplex)
    C = np.array([0.0, 0.0, 0.0])
    H_vektoren = create_tetrahedron_vectors()

    # Constraint 1: Schwerpunkt-Regel
    schwerpunkt = C - (1.0 / 4.0) * sum(H_vektoren)
    assert np.allclose(schwerpunkt, 0.0, atol=1e-5)

    # GA Wedge-Produkt Validierung für identische Sub-Tetraeder-Volumina
    # Übertragung der Vektoren in die Algebra
    h1, h2, h3, h4 = [eo + h[0]*e1 + h[1]*e2 + h[2]*e3 + 0.5*np.dot(h,h)*einf for h in H_vektoren]
    c_ga = eo # Ursprung

    vol1 = (h1 - c_ga) ^ (h2 - c_ga) ^ (h3 - c_ga)
    vol2 = (h2 - c_ga) ^ (h3 - c_ga) ^ (h4 - c_ga)

    assert np.allclose(abs(vol1), abs(vol2), atol=1e-4)

def test_ethene_planar_constraint():
    """Überprüft die Kantenparallelität und Planarität bei einer Doppelbindung (Ethen)."""
    # Vektoren zweier gebundener Kohlenstoffe (Kanten-Teilung)
    # Wenn die SVD-Engine korrekt rechnet, müssen die Richtungsvektoren koplanar sein
    W_A1 = np.array([0.3, 0.4, 0.5])
    W_A2 = np.array([0.3, -0.4, 0.5])

    # Perfekt gespiegeltes System durch Kanten-Teilung-Constraint
    W_B1 = -W_A1
    W_B2 = -W_A2

    # Det-Bedingung für Koplanarität (Klassische Vektorrechnung)
    matrix = np.vstack([W_A1, W_A2, W_B1])
    assert np.allclose(np.linalg.det(matrix), 0.0, atol=1e-5)

  '''

'''
create_tetrahedron_vectors()
'''

# test_methane_volume_constraint()

# test_ethene_planar_constraint()

"""# Whitepaper: Kugelwolkenmodell (KWM) - Engine V 1.0.0
**Architektur- und Geometrie-Dokumentation des interaktiven 3D-Baukastens**

---

## 1. Die mathematische Engine

Das System löst das Problem der optimalen räumlichen Ausrichtung von zwei 3D-Körpern (Tetraedern) basierend auf einer dynamischen Anzahl von Bindungspunkten (Kugelwolken).

### 1.1 Translations-Skalar (Bindungslänge)
Der euklidische Abstand $d$ zwischen den Atomkernen ist diskretisiert nach der Bindungsordnung (Anzahl der ausgewählten Wolken $n$):
* **$n=3$:** $d = 1.02$ (Flächen-Teilung / Dreifachbindung)
* **$n=2$:** $d = 1.12$ (Kanten-Teilung / Doppelbindung)
* **$n=1$:** $d = 1.25$ (Punkt-Teilung / Einfachbindung)

### 1.2 Der Richtungsvektor (Die Bindungsachse)
Die normalisierte Bindungsachse $\vec{u}$ (Länge 1) wird berechnet:
* **Wenn Atom A starr ist:** Der Vektor ergibt sich aus dem Schwerpunkt der im Raum fixierten, ausgewählten Wolken von A:
  $$\vec{u} = \frac{\sum \vec{c}_{A\_global}}{\|\sum \vec{c}_{A\_global}\|}$$
* **Wenn Atom A frei ist:** Der Vektor ist die direkte Sichtlinie:
  $$\vec{u} = \frac{\vec{p}_B - \vec{p}_A}{\|\vec{p}_B - \vec{p}_A\|}$$

### 1.3 Zielerfassung Atom A (Rodrigues-Formel)
Zwingt die freien Wolken von Atom A exakt auf die Achse $\vec{u}$. Mit dem normalisierten lokalen Wolkenzentrum $\vec{z}_{local}$ berechnen wir die Rotationsachse $\vec{v}$ (Kreuzprodukt) und den Winkelkosinus $c$ (Skalarprodukt):
$$\vec{v} = \vec{z}_{local} \times \vec{u}$$
$$c = \vec{z}_{local} \cdot \vec{u}$$
Mit der schiefsymmetrischen Matrix $K$ (aus $\vec{v}$) erzeugt die Rodrigues-Formel die Matrix $R_A$:
$$R_A = I + K + K^2 \frac{1 - c}{\|\vec{v}\|^2}$$

### 1.4 Kabsch-Algorithmus (Die SVD-Ausrichtung für Atom B)
Atom B muss so rotiert werden, dass seine Start-Vektoren ($B_{start}$) auf die invertierten, globalen Vektoren von Atom A ($B_{ziel} = -R_A A_{start}$) zeigen. Wir berechnen die Kovarianzmatrix $H$ und zerlegen sie (Singularwertzerlegung):
$$H = B_{start}^T \cdot B_{ziel}$$
$$U, \Sigma, V^T = \text{SVD}(H)$$
Die optimale Rotationsmatrix ist:
$$R_B = V \cdot U^T$$
*(Anti-Spiegelungs-Schutz: Ist $\det(R_B) < 0$, wird die letzte Spalte von $V$ mit $-1$ multipliziert).*

### 1.5 Geometrische Restriktionen (Der Chemie-Faktor)
* **$n=2$ (Koplanarität):** Der Matrix $H$ wird ein dritter, orthogonaler Vektor $\vec{n} = \vec{w}_1 \times \vec{w}_2$ hinzugefügt, um das Rollen um die Achse zu blockieren (Schienen-Trick).
* **$n=3$ (Anti-Umklapp & Torsion):** Ist das resultierende Molekül nach innen geklappt ($\vec{zentrum}_B \cdot \vec{u} > 0$), wird Atom B um $180^\circ$ um eine zu $\vec{u}$ orthogonale Achse gespiegelt. Zuletzt wird eine Torsionsmatrix $R_{torsion}$ ($60^\circ$-Drehung um $\vec{u}$) auf $R_B$ angewendet, damit die Wolken energetisch korrekt "auf Lücke" stehen.

---

## 2. Der System-Pseudocode

Dieser Pseudocode dokumentiert die logische Architektur des `/binde`-Endpoints.

```text
FUNKTION binde_atome(Atom_A, Atom_B, wolken_A_auswahl, wolken_B_auswahl):

    // --- SETUP & SORTIERUNG ---
    anzahl_wolken = LÄNGE(wolken_A_auswahl)
    lokale_A = HOLE_VEKTOREN(Atom_A, wolken_A_auswahl)
    lokale_B = HOLE_VEKTOREN(Atom_B, wolken_B_auswahl)
    lokale_B = SORTIERE_GEGEN_UEBERKREUZ(lokale_A, lokale_B)

    WENN anzahl_wolken == 3: abstand = 1.02
    WENN anzahl_wolken == 2: abstand = 1.12
    SONST:                   abstand = 1.25

    ist_A_zentralatom = PRÜFE_OB_BEREITS_GEBUNDEN(Atom_A)

    // --- 1. ACHSE BESTIMMEN ---
    WENN ist_A_zentralatom:
        globale_A_auswahl = ROTIERE_VEKTOREN(Atom_A.rotation, lokale_A)
        achse = NORMALISIERE( BERECHNE_MITTELPUNKT(globale_A_auswahl) )
    SONST:
        achse = NORMALISIERE(Atom_B.position - Atom_A.position)

    // B wird verschoben
    Atom_B.position = Atom_A.position + (achse * abstand)

    // --- 2. ATOM A ROTIEREN (Nur Erstkontakt) ---
    WENN NICHT ist_A_zentralatom:
        zentrum_A_lokal = NORMALISIERE( BERECHNE_MITTELPUNKT(lokale_A) )
        drehachse = KREUZPRODUKT(zentrum_A_lokal, achse)
        winkel = SKALARPRODUKT(zentrum_A_lokal, achse)
        Atom_A.rotation = RODRIGUES_ROTATION(drehachse, winkel)

    // Globale Zielkoordinaten für B fixieren (immer invertiert zu A)
    globale_A_auswahl = ROTIERE_VEKTOREN(Atom_A.rotation, lokale_A)
    ziel_B = INVERTIERE(globale_A_auswahl)
    start_B = lokale_B

    // --- 3. SPEZIFISCHE BINDUNGSLOGIK (SVD) ---
    WENN anzahl_wolken == 1:
        kovarianz = OUTER_PRODUCT(start_B, ziel_B)
        Atom_B.rotation = SVD_ABGLEICH(kovarianz)

    WENN anzahl_wolken == 2:
        normalenvektor_A = KREUZPRODUKT(ziel_B[0], ziel_B[1])
        normalenvektor_B = KREUZPRODUKT(start_B[0], start_B[1])
        FÜGE_HINZU(ziel_B, normalenvektor_A)
        FÜGE_HINZU(start_B, normalenvektor_B)
        
        kovarianz = MATRIX_MULTIPLIKATION(TRANSIONIERE(start_B), ziel_B)
        Atom_B.rotation = SVD_ABGLEICH(kovarianz)

    WENN anzahl_wolken == 3:
        kovarianz = MATRIX_MULTIPLIKATION(TRANSIONIERE(start_B), ziel_B)
        basis_rotation = SVD_ABGLEICH(kovarianz)

        // Anti-Umklapp-Schutz (Schnitzel-Flip)
        zentrum_B_test = BERECHNE_MITTELPUNKT( ROTIERE_VEKTOREN(basis_rotation, start_B) )
        WENN SKALARPRODUKT(zentrum_B_test, achse) > 0:
            flip_matrix = BERECHNE_180_GRAD_ORTHO_ROTATION(achse)
            basis_rotation = MATRIX_MULTIPLIKATION(flip_matrix, basis_rotation)

        // Torsions-Korrektur (60° auf Lücke)
        torsions_matrix = BERECHNE_ACHSEN_ROTATION(achse, 60_GRAD)
        Atom_B.rotation = MATRIX_MULTIPLIKATION(torsions_matrix, basis_rotation)

    // --- 4. ABSCHLUSS ---
    SETZE_ELEKTRONEN_STATUS(Atom_A, wolken_A_auswahl, GEBUNDEN)
    SETZE_ELEKTRONEN_STATUS(Atom_B, wolken_B_auswahl, GEBUNDEN)

    GIB_ZURÜCK Erfolg

Clifford Implementierung /binde Endpoint
"""

'''
from clifford.g3 import * # Importiert die Clifford-Algebra für 3D
import numpy as np

def binde_atome_ga(atom_A, atom_B, wolken_A_ids, wolken_B_ids):
    # 1. Konvertierung der Numpy-Vektoren in Clifford-Multivektoren
    def to_ga(vec): return vec[0]*e1 + vec[1]*e2 + vec[2]*e3

    punkte_A = [to_ga(atom_A.wolken[i].richtung_lokal) for i in wolken_A_ids]
    punkte_B = [to_ga(atom_B.wolken[i].richtung_lokal) for i in wolken_B_ids]

    # 2. Bindungsachse (als Vektor)
    # Falls A schon gebunden ist: Fokus auf Schwerpunkt der gewählten Wolken
    zentrum_A = sum(punkte_A) / len(punkte_A)
    # Einbindung der Rotation von A (Sandwich: R * v * ~R)
    achse = atom_A.rotor * zentrum_A * ~atom_A.rotor
    achse = achse.normal() # Normierung zur Einheitsachse

    # 3. Optimale Rotation für Atom B finden
    # Wir bilden den Rotor, der Punkte_B auf die Invertierung von A ausrichtet
    # GA ersetzt hier den SVD-Kabsch-Algorithmus durch Versoren

    ziel_B = -(atom_A.rotor * sum(punkte_A) * ~atom_A.rotor)
    start_B = sum(punkte_B)

    # In GA: Die Rotation zwischen zwei Vektoren wird durch den
    # Logarithmus des Rotors (Bivektor) direkt berechnet
    bivektor = start_B ^ ziel_B
    angle = np.arccos(min(max((start_B | ziel_B).value, -1), 1))
    rotor_B = exp(-0.5 * angle * bivektor.normal())

    # 4. Geometrische Restriktionen
    if len(wolken_A_ids) == 2:
        # Doppelbindung: Der Bivektor der Ebene erzwingt Koplanarität
        ebene = punkte_B[0] ^ punkte_B[1]
        # Wir zwingen den Rotor_B in die Ebene durch Projektion
        # Hier geschieht der "Schienen-Trick" automatisch durch den Bivektor

    elif len(wolken_A_ids) == 3:
        # Dreifachbindung: Torsion (60 Grad auf Lücke)
        # Torsions-Rotor um die Bindungsachse
        torsion = exp(-0.5 * (np.radians(60)) * achse)
        rotor_B = torsion * rotor_B

    # 5. Finale Transformation
    # Atom B wird durch den kombinierten Rotor gedreht
    atom_B.rotor = rotor_B
    atom_B.position = atom_A.position + (achse.value * fester_abstand)

    return {"status": "success", "info": "GA-Bindung berechnet"}
    '''

'''
# Hilfsfunktion für die Schnittstelle
def rotor_to_threejs_matrix(rotor):
    # Wandelt den GA-Rotor in die für Three.js nötige 3x3 oder 4x4 Matrix
    return rotor.matrix()
'''

"""Warum das für dein Projekt ein Gewinn ist:

- GA Rotor um Achse

**Verschmelzung von SVD und Geometrie**: Anstatt die Kovarianzmatrix H zu bilden und per SVD zu zerlegen, berechnest du in der GA direkt den Bivektor der Rotation (start_B ^ ziel_B). Das ist geometrisch intuitiver: Du sagst der Algebra einfach, in welcher Ebene die Drehung stattfinden soll, und der Rotor erledigt den Rest.Der Torsions-Rotor: In deinem alten Code hast du eine Rotationsmatrix R_torsion mit Sinus/Cosinus und schiefsymmetrischen Matrizen mühsam manuell aufgebaut. In Clifford ist exp(-0.5 * angle * achse) die exakte Definition einer Rotation. Das ist weniger fehleranfällig.

**Wegfall der Determinanten-Prüfung**: Da ein Rotor in der Geometrischen Algebra eine invariante Größe ist, tritt das Problem der "Punktspiegelung vs. Drehung" (dein Anti-Spiegelungs-Schutz) in der Logik gar nicht erst auf. Ein Rotor beschreibt immer eine reine Rotation innerhalb der SO(3)-Gruppe.

Ein wichtiger Hinweis für die Umsetzung:Da clifford intern mit Multivektoren (einer Kombination aus Skalar, Vektor, Bivektor und Trivektor) arbeitet, musst du beim Schreiben in deine Datenbank (oder beim Senden an Three.js) den Multivektor wieder in eine $3 \times 3$ Matrix konvertieren. Die Bibliothek bietet dafür rotor.matrix() an, was genau die Schnittstelle zu deinem Three.js-Frontend sauber hält.
"""

'''
from fastapi import FastAPI
from clifford.g3 import *
import numpy as np

# Voraussetzung: clifford muss installiert sein (!pip install clifford)

@app.post("/binde")
def binde_atome(daten: dict):
    atom_A = WELT_ZUSTAND[daten["atom_A_id"]]
    atom_B = WELT_ZUSTAND[daten["atom_B_id"]]
    wolken_A_ids = daten["wolken_A_ids"]
    wolken_B_ids = daten["wolken_B_ids"]

    anzahl = len(wolken_A_ids)

    # 1. HELFER: Numpy -> Clifford Vektor
    def to_vec(nparr): return nparr[0]*e1 + nparr[1]*e2 + nparr[2]*e3

    # Lokale Vektoren laden
    A_lokal = [to_vec(np.array(atom_A.wolken[i].richtung_lokal)) for i in wolken_A_ids]
    B_lokal = [to_vec(np.array(atom_B.wolken[i].richtung_lokal)) for i in wolken_B_ids]

    # Dynamischer Abstand
    abstand = {3: 1.02, 2: 1.12}.get(anzahl, 1.25)

    # 2. BINDUNGSACHSE (GA-natürlich)
    # Wenn A gebunden ist, ist die Achse durch die aktuelle Rotation von A fixiert
    if any(w.elektronen == 3 for w in atom_A.wolken):
        # A_rotor ist der in Atom_A gespeicherte GA-Rotor
        achse_vec = atom_A.rotor * sum(A_lokal) * ~atom_A.rotor
    else:
        # Falls frei, Einflugvektor nutzen
        diff = atom_B.position - atom_A.position
        achse_vec = to_vec(diff / np.linalg.norm(diff))

    achse_vec = achse_vec.normal()

    # 3. ROTATION BERECHNEN (Rotor-Sandwich)
    # Ziel: B_start soll auf -achse zeigen
    # Wir berechnen den Rotor direkt über das äußere Produkt (Bivektor-Ebene)
    target = -achse_vec
    source = sum(B_lokal) / anzahl

    # Bivektor der Drehebene
    bivektor = (source ^ target).normal()
    winkel = np.arccos(min(max((source | target).value, -1), 1))

    # Rotor B: Die Rotation von B
    rotor_B = exp(-0.5 * winkel * bivektor)

    # 4. GEOMETRISCHE KORREKTUREN
    if anzahl == 3:
        # Torsion: 60 Grad Rotation um die Bindungsachse (GA: Multiplikation der Rotoren)
        torsion = exp(-0.5 * np.radians(60) * achse_vec)
        rotor_B = torsion * rotor_B

    # 5. ANWENDUNG & KONVERTIERUNG
    atom_B.rotor = rotor_B
    atom_B.position = atom_A.position + (achse_vec.value * abstand)

    # Status setzen
    for i in wolken_A_ids: atom_A.wolken[i].elektronen = 3
    for i in wolken_B_ids: atom_B.wolken[i].elektronen = 3

    return {
        "status": "success",
        "debug": "GA-Bindung erfolgreich",
        "matrix": rotor_B.matrix().tolist() # Schnittstelle für Three.js
    }
    '''